"""Domain models for Technical Analysis system."""

from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, Optional

from pydantic import BaseModel, Field, field_validator


class Timeframe(str, Enum):
    """Supported timeframes for analysis."""
    
    M1 = "1m"
    M5 = "5m"
    M15 = "15m"
    M30 = "30m"
    H1 = "1h"
    H4 = "4h"
    D1 = "1d"
    W1 = "1w"
    MN1 = "1M"
    
    def to_seconds(self) -> int:
        """Convert timeframe to seconds."""
        mapping = {
            "1m": 60,
            "5m": 300,
            "15m": 900,
            "30m": 1800,
            "1h": 3600,
            "4h": 14400,
            "1d": 86400,
            "1w": 604800,
            "1M": 2592000,  # Approximate
        }
        return mapping[self.value]


class SignalType(str, Enum):
    """Types of trading signals."""
    
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE = "CLOSE"


class Symbol(BaseModel):
    """Stock/Asset symbol information."""
    
    ticker: str = Field(..., description="Symbol ticker (e.g., AAPL)")
    name: str = Field(..., description="Full company/asset name")
    exchange: str = Field(..., description="Exchange where traded")
    sector: Optional[str] = Field(None, description="Market sector")
    market_cap: Optional[int] = Field(None, description="Market capitalization")
    
    @field_validator("ticker")
    @classmethod
    def ticker_uppercase(cls, v: str) -> str:
        """Ensure ticker is uppercase."""
        if not v.isupper():
            raise ValueError("Ticker must be uppercase")
        return v
    
    def __eq__(self, other: Any) -> bool:
        """Check equality based on ticker."""
        if not isinstance(other, Symbol):
            return False
        return self.ticker == other.ticker


class OHLCV(BaseModel):
    """Open, High, Low, Close, Volume price data."""
    
    symbol: str = Field(..., description="Symbol ticker")
    timestamp: datetime = Field(..., description="Candle timestamp")
    open: Decimal = Field(..., description="Opening price")
    high: Decimal = Field(..., description="Highest price")
    low: Decimal = Field(..., description="Lowest price")
    close: Decimal = Field(..., description="Closing price")
    volume: int = Field(..., description="Trading volume")
    
    @field_validator("volume")
    @classmethod
    def volume_non_negative(cls, v: int) -> int:
        """Ensure volume is non-negative."""
        if v < 0:
            raise ValueError("Volume must be non-negative")
        return v
    
    @field_validator("low")
    @classmethod
    def validate_high_low(cls, v: Decimal, info) -> Decimal:
        """Ensure high >= low."""
        if "high" in info.data and info.data["high"] < v:
            raise ValueError("High must be >= Low")
        return v
    
    @property
    def typical_price(self) -> Decimal:
        """Calculate typical price (HLC/3)."""
        return (self.high + self.low + self.close) / 3
    
    @property
    def range(self) -> Decimal:
        """Calculate price range."""
        return self.high - self.low


class Indicator(BaseModel):
    """Technical indicator definition."""
    
    name: str = Field(..., description="Short name (e.g., RSI)")
    full_name: str = Field(..., description="Full indicator name")
    category: str = Field(..., description="Indicator category")
    parameters: Dict[str, Any] = Field(..., description="Default parameters")
    description: Optional[str] = Field(None, description="Indicator description")
    
    class Config:
        """Pydantic configuration."""
        
        json_encoders = {
            Decimal: str,
        }


class IndicatorValue(BaseModel):
    """Calculated indicator value at a point in time."""
    
    symbol: str = Field(..., description="Symbol ticker")
    timestamp: datetime = Field(..., description="Calculation timestamp")
    indicator: str = Field(..., description="Indicator name")
    timeframe: Timeframe = Field(..., description="Timeframe used")
    value: Decimal = Field(..., description="Primary indicator value")
    parameters: Dict[str, Any] = Field(..., description="Parameters used")
    components: Optional[Dict[str, Decimal]] = Field(
        None, description="Additional indicator components"
    )
    
    class Config:
        """Pydantic configuration."""
        
        json_encoders = {
            Decimal: str,
        }


class Signal(BaseModel):
    """Trading signal generated by strategy."""
    
    symbol: str = Field(..., description="Symbol ticker")
    timestamp: datetime = Field(..., description="Signal timestamp")
    signal_type: SignalType = Field(..., description="Type of signal")
    strategy: str = Field(..., description="Strategy that generated signal")
    confidence: Decimal = Field(..., description="Signal confidence (0-1)")
    price: Decimal = Field(..., description="Price at signal generation")
    indicators: Dict[str, Decimal] = Field(
        default_factory=dict, description="Indicator values at signal time"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None, description="Additional signal metadata"
    )
    
    @field_validator("confidence")
    @classmethod
    def validate_confidence(cls, v: Decimal) -> Decimal:
        """Ensure confidence is between 0 and 1."""
        if not (0 <= v <= 1):
            raise ValueError("Confidence must be between 0 and 1")
        return v
    
    class Config:
        """Pydantic configuration."""
        
        json_encoders = {
            Decimal: str,
        }